blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail, name='post_detail'),
    path('<int:post_id>', views.add_comment, name='add_comment'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add_to_cart/<int:product_id>', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:product_id>', views.remove_from_cart,
         name='remove_from_cart'),
    path('clear_cart', views.clear_cart, name='clear_cart'),
    path('', views.cart_details, name='cart_details'),
]

julisa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from blog import views as blog_views

urlpatterns = [
    path('', blog_views.index, name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('courses/', include('courses.urls', namespace='courses')),
    path('summernote/', include('django_summernote.urls')),
    path('nested_admin/', include('nested_admin.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')

class Category(models.Model):
    name = models.CharField('Название', max_length=250)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField()
    image = models.ImageField(upload_to='categories/images/',
                              blank=True)


    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name + ' | ' + self.slug

    def get_absolute_url(self):
        return reverse('blog:index', args=[self.slug,])

class Subcategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField()
    image = models.ImageField(upload_to='categories/subcategories/images',
                              blank=True)

    class Meta:
        ordering = ['name',]
        verbose_name = 'Подкатегория'
        verbose_name_plural = 'Подкатегории'

    def __str__(self):
        return self.name


class Post(models.Model):
    status_choices = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    category = models.ForeignKey(Category, on_delete=models.CASCADE,
                                 related_name='posts')
    title = models.CharField('Заголовок', max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='blog_posts')
    thumbnail_image = models.ImageField(upload_to='post/thumbnails',
                                        blank=True)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=status_choices,
                              default='draft')
    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ('-publish',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='comments')
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             related_name='comments')
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    published = models.BooleanField(default=True)

    class Meta:
        ordering = ['-created']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return f'{self.author} прокомментировал пост: {self.post}. {self.created}'

blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.shortcuts import redirect
from .models import Post, Category, Subcategory, Comment
from .forms import CommentForm

# Create your views here.

def index(request, slug=None):
    recent_posts = Post.published.all()[:3]
    context = {'recent_posts': recent_posts}
    return render(request, 'blog/index.html', context)

def post_list(request):
    posts = Post.published.all()
    context = {'posts': posts}
    return render(request, 'blog/post/list.html', context)

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published',
                             publish__year=year, publish__month=month,
                             publish__day=day)
    form = CommentForm()
    comments = post.comments.filter(published=True)
    context = {'post': post,
               'comments': comments,
               'form': form}
    return render(request, 'blog/post/detail.html', context)

def add_comment(request, post_id):
    if request.method == 'POST':
        post = get_object_or_404(Post, id=post_id)
        author = get_object_or_404(User, id=1)
        form = CommentForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            body = cd['body']
            comment = Comment.objects.create(author=author, post=post,
                                             body=body)
            comment.save()
            return redirect('blog:post_detail', post.publish.year,
                                                post.publish.month,
                                                post.publish.day,
                                                post.slug,
                                                )

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Arimo|Lora" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'blog/css/julisa.css' %}">
  </head>
  <body>
    <div class="top-menu">
        <i class="top-menu-icon fab fa-instagram fa-2x"></i>
        <i class="top-menu-icon fab fa-vk fa-2x"></i>
        <div class="top-menu-slogan">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit.
        </div>
        <span class="top-menu-option">Главная</span>
        <span class="top-menu-option">Регистрация</span>
        <span class="top-menu-option">
          {% if user.is_authenticated %}
            <a href="{% url 'logout' %}">Выход</a>
          {% else %}
            <a href="{% url 'login' %}">Вход</a>
          {% endif %}
        </span>
        <a href="{% url 'cart:cart_details' %}">
          <i class="top-menu-icon fas fa-shopping-cart"></i>
        </a>
    </div>
    <hr>

    <div class="nav-wrapper">
      <div class="nav-container">
        <img class="logo" src="{% static 'blog/images/Logo.jpg' %}" alt="">
        <!-- <span class="navbar-option">0-1,5 года</span>
        <span class="navbar-option">1,5-3 года</span>
        <span class="navbar-option">Билингвизм</span>
        <span class="navbar-option">Мамины заметки</span> -->
        <div class="dropdown">
         <button class="dropbtn">0-1,5 года <i class="fas fa-caret-down"></i></button>
         <div class="dropdown-content">
           <a href="#">Library</a>
           <a href="#">Toys</a>
           <a href="#">Multimedia</a>
         </div>
        </div>
        <div class="dropdown">
         <button class="dropbtn">1,5-3 года <i class="fas fa-caret-down"></i></button>
         <div class="dropdown-content">
           <a href="#">Library</a>
           <a href="#">Toys</a>
           <a href="#">С чего начать</a>
           <a href="#">Multimedia</a>
         </div>
        </div>
        <span class="navbar-option">Билингвизм</span>
        <div class="dropdown">
         <button class="dropbtn">Мамины заметки <i class="fas fa-caret-down"></i></button>
         <div class="dropdown-content">
           <a href="#">Точка зрения</a>
           <a href="#">Полезные online-ресурсы</a>
           <a href="#">Алиса: дневник речевого развития</a>
         </div>
        </div>
      </div>
    <div class="shop-button-wrapper">
        <div class="shop-button-container">
          <div class="shop-button"><a href="{% url 'shop:index' %}">SHOP</a></div>
        </div>
      </div>
    </div>
    <div class="container">
    {% block content %}
    {% endblock %}
    </div>

    <!-- <div class="faq-container">
      <div class="faq-entry">
        Как распределить время?
      </div>
      <div class="faq-entry">
        С чего начать?
      </div>
    </div>
    <div class="faq-container">

      <div class="faq-entry">
        Что такое билингвизм и полезен ли он?
      </div>
      <div class="faq-entry">
        Как распределить время?
      </div>
    </div>
    <div class="faq-container">
      <div class="faq-entry">
        Как распределить время?
      </div>
    </div> -->

  </body>
</html>

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}

<div class="row">
  <div class="col-12 text-center">
    <h2>FAQ</h2>
  </div>
</div>
<div class="row">
  <div class="faq-entry col-lg-6 col-12 mx-auto mt-2 text-center">
    Как распределить время?
  </div>
  <div class="faq-entry col-lg-6 col-12 mx-auto mt-2">
    С чего начать?
  </div>
</div>
<div class="row">
  <div class="faq-entry col-lg-6 col-12 mx-auto mt-2">
    Что такое билингвизм и полезен ли он?
  </div>
  <div class="faq-entry col-lg-6 col-12 mx-auto mt-2">
    Как распределить время?
  </div>
</div>
<div class="row">
  <div class="faq-entry col-lg-6 col-12 mx-auto mt-2">
    Как распределить время?
  </div>
  <div class="faq-entry col-lg-6 col-12 mx-auto mt-2">
    Как распределить время?
  </div>
</div>
<div class="row mt-4">
  <div class="col-12 text-center">
    <h2>Последние статьи</h2>
  </div>
</div>
<div class="row mt-4">
  <div class="last-article col-lg-4 col-12 text-center">
    <img class="last-article-image img-fluid m-0" src="{% static 'blog/images/confused-kid.jpg' %}" alt="">
    <h4>Название статьи</h4>
    <p class="text-justify">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
  <div class="last-article col-lg-4 col-12 text-center">
    <img class="last-article-image img-fluid m-0" src="{% static 'blog/images/random-kid.jpg' %}" alt="">
    <h4>Название статьи</h4>
    <p class="text-justify">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
  <div class="last-article col-lg-4 col-12 text-center">
    <img class="last-article-image img-fluid m-0" src="{% static 'blog/images/random-kid2.jpg' %}" alt="">
    <h4>Название статьи</h4>
    <p class="text-justify">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>

</div>

{% endblock %}